### ISSUE TITLE
getting a weird error

### ISSUE THREAD

**Issue by kevinsalter** [pre-commit/mirrors-coffeelint#2]
I'm getting this error when running the coffeelint pre-commit, any ideas?!

```
❯ [issues/2] ✗ git commit -m "testing"
coffeelint...........................................................................................................................Failed
hookid: coffeelint

/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/coffeelint.js:1736
        previousToken = tokenApi.peek(-1)[0];
                                         ^
TypeError: Cannot read property '0' of null
  at NoImplicitBraces.module.exports.NoImplicitBraces.lintToken (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/coffeelint.js:1736:42)
  at LexicalLinter.module.exports.LexicalLinter.lintToken (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/coffeelint.js:679:43)
  at LexicalLinter.module.exports.LexicalLinter.lint (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/coffeelint.js:647:20)
  at Object.coffeelint.lint (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/coffeelint.js:538:31)
  at lintFiles (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/commandline.js:141:44)
  at Object.<anonymous> (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/commandline.js:307:21)
  at Object.<anonymous> (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/lib/commandline.js:312:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/kevinsalter/.pre-commit/repo2osoDV/node_env/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by kevinsalter** [comment]
i think i've fixed it locally, thanks
